services:
  postgres:
    image: postgres:15
    container_name: notification_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notifications
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - edns_network

  redis:
    image: redis:8-alpine
    container_name: notification_redis
    ports:
      - "6379:6379"
    networks:
      - edns_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - edns_network

  api:
    build:
      context: .
      dockerfile: api-service/Dockerfile
    container_name: edns_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - edns_network

  worker:
    build:
      context: .
      dockerfile: worker-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - postgres
      - mailpit
    networks:
      - edns_network

  websocket:
    build:
      context: .
      dockerfile: websocket-service/Dockerfile
    container_name: websocket_service
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - worker
    networks:
      - edns_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api
      - worker
      - websocket
    networks:
      - edns_network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - edns_network

volumes:
  postgres_data:
  grafana_data:

networks:
  edns_network:
    driver: bridge
