services:
  api:
    build:
      context: .
      dockerfile: api-service/Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app/api-service
    command: air
    ports:
      - "8080:8080"

  worker:
    build:
      context: .
      dockerfile: worker-service/Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app/worker-service
    command: air
    ports:
      - "8081:8081"

  websocket:
    build:
      context: .
      dockerfile: websocket-service/Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app/websocket-service
    command: air
    ports:
      - "8082:8082"

volumes:
  postgres_data:
