services:
  postgres:
    image: postgres:15
    container_name: notification_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notifications
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: notification_redis
    ports:
      - "6379:6379"
  
  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: edns_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
  
  worker:
    build:
      context: ./worker-service
      dockerfile: Dockerfile
    container_name: edns_worker
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data:
